### ISSUE TITLE
Feature : Remove expiry as a response in refresh and login endpoints.

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#1009]
**Is your feature request related to a problem? Please describe.**
 
 The access_expiry and refresh_expiry aren't fields that are required on the front end as they can be accessed by decoding the token.

**Describe the solution you'd like**

Remove them as responses from the refresh and login endpoints.

**Additional context**

They are not being used in the android app as of now.

**Comment by b-thebest** [comment]
Hello sir,
Could I take up this issue. I have experience of working with REST APIs and would like to start contributing using this issue.
Thank you

**Comment by epicadk** [comment]
> Hello sir,
> Could I take up this issue. I have experience of working with REST APIs and would like to start contributing using this issue.
> Thank you

Hello @b-thebest , welcome to the organisation. This issue still needs to be approved by @isabelcosta .You can try pinging her on zulip In the mean time you can start working on issue that have a label status available . Goodluck : )

**Comment by b-thebest** [comment]
@epicadk I don't use Zulip and also don't have idea about that software. How can I reach her

**Comment by epicadk** [comment]
@b-thebest You can use the website for zulip as well. It is mentioned in the contact section of the readme. https://github.com/anitab-org/mentorship-backend#contact. If you still can't sign up you can wait till she responds here but it may take a little while longer.

**Comment by b-thebest** [comment]
@epicadk Private message is not allowed in Zulip for organization. I have mailed to opensource@anitab.org

**Comment by isabelcosta** [comment]
@b-thebest regarding our projects, the best way to reach out to us in on Zulip or tag us on GitHub (in my case: @isabelcosta). Talking about project development is supposed to happen in our community in the open (public) :) So that everyone can benefit from the questions you have and the answers you get. So feel free to post on the [#mentorship-system](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system) stream on Zulip and reach out to the wider community. You can learn more about why private messaging is disabled in our [FAQ](https://github.com/anitab-org/documentation/blob/master/frequently-asked-questions.md). Email communication is mostly for sensitive matters (e.g.: violation of code of conduct of community members)

Here's our zulip: https://anitab-org.zulipchat.com/ :)

**Comment by isabelcosta** [comment]
@epicadk about this issue 🤔 I agree. so this data can be taken from the token right? Also, these fields are not yet being used by any frontend right? Will make available then

**Comment by epicadk** [comment]
> @epicadk about this issue 🤔 I agree. so this data can be taken from the token right?

Yep , it can .

**Comment by isabelcosta** [comment]
Ok, will assign the issue to @b-thebest then :)

**Comment by epicadk** [comment]
Sorry accidentally closed it. I'm still getting use to GitHub mobile 😅

**Comment by b-thebest** [comment]
Thank you for assignment and kind information about reaching anitab
contributors.
From next time onwards I will be reaching out only through Zulip.

**Comment by b-thebest** [comment]
Hello @epicadk Please review pull request made by me and merge it.
