### ISSUE TITLE
Improve Github actions

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#1067]
### Is your feature request related to a problem? Please describe.

Currently we have two separate workflows for lint and build/tests 

### Describe the solution you'd like

Have them in the same workflow. Run the lint check before the tests.

**Comment by isabelcosta** [comment]
@epicadk would they show up as different checks in here?

![image](https://user-images.githubusercontent.com/11148726/113482819-3defd600-9498-11eb-8d64-b3b74d72513d.png)

Because I think they should appear separately like that, I don't mind gathering in the same workflow file, I just want them to show separately. Would that still show like that?

**Comment by epicadk** [comment]
> @epicadk would they show up as different checks in here?
> 
> ![image](https://user-images.githubusercontent.com/11148726/113482819-3defd600-9498-11eb-8d64-b3b74d72513d.png)
> 
> Because I think they should appear separately like that, I don't mind gathering in the same workflow file, I just want them to show separately. Would that still show like that?

Nope they wouldn't. I just think that if the lint check fails then we shouldn't waste resources.

**Comment by epicadk** [comment]
So basically if there is a way to cancel the build tests if the lint check fails I would be open to that solution as well. 
If this is better then I'll update the issue. However won't be a good first issue so I'll remove that tag.

**Comment by vj-codes** [comment]
> So basically if there is a way to cancel the build tests if the lint check fails I would be open to that solution as well.
> If this is better then I'll update the issue. However won't be a good first issue so I'll remove that tag.

@epicadk there is a way but both checks should be included in one workflow,
if we keep linting code as the first step and use `if statement` and when true, it'll run the next step, [check ref here](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions)
However, I'm not sure if it will work as the documentation for black clearly mentions having a file named `black.yml` for gh action also I am more inclined to having both workflows separate but if decided otherwise I would like to work on this

**Comment by epicadk** [comment]
> > So basically if there is a way to cancel the build tests if the lint check fails I would be open to that solution as well.
> > If this is better then I'll update the issue. However won't be a good first issue so I'll remove that tag.
> 
> @epicadk there is a way but both checks should be included in one workflow,
> if we keep linting code as the first step and use `if statement` and when true, it'll run the next step, [check ref here](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions)
> However, I'm not sure if it will work as the documentation for black clearly mentions having a file named `black.yml` for gh action also I am more inclined to having both workflows separate but if decided otherwise I would like to work on this

That is very strange I don't think the name of the workflow file should not matter. Can you link the doc here?

**Comment by vj-codes** [comment]
Even I thought the same as the basic requirement is just a yaml file but it's mentioned there https://github.com/psf/black#github-actions

**Comment by epicadk** [comment]
> Even I thought the same as the basic requirement is just a yaml file but it's mentioned there https://github.com/psf/black#github-actions

It should work with any other name. Or we could just do pip install black.

**Comment by vj-codes** [comment]
ohhh then I can give it a try , if it works we can make a decision in the sync up session 
Can you assign this to me please :)

**Comment by epicadk** [comment]
Done : ). Good luck.

**Comment by epicadk** [comment]
@vj-codes can you send in the pr. We can ask isabel to take a look there.  Also include `cancel previous` if possible.

**Comment by vj-codes** [comment]
@epicadk can you send a resource for it , because the one I [read](https://github.com/marketplace/actions/cancel-previous-workflow-runs) says we can't use it if the PR comes from a fork branch

**Comment by vj-codes** [comment]
Update : will create a PR tomr without cancel previous
