### ISSUE TITLE
Create GET /home API to get some statistics about the user usage

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#120]
## Description
As a developer,
I need GET /home API,
so that I can return to the frontend some information regarding the user's app usage.

This API is needed to enhance the Home Screen of the Android application issue https://github.com/systers/mentorship-android/issues/20

**Data to be returned:**
- \# pending requests
- \# accepted requests
- \# completed relations
- \# cancelled relations
- \# rejected requests
- ~3 recent achievements

### Update [Required]
- [ ] Create DAO function for this
- [ ] Create API resource for this
- [ ] Create tests for this

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by haroldadmin** [comment]
@isabelcosta I would like to work on this issue.

Since the home endpoint would return the data for a user, it makes sense to implement it as an extension on the user namespace. I think that we can create an end point /home in the user resource, and make it a jwt required type of method. We can get the user Id using the jwt token, and use it to return the statistics.

Regarding the achievements, I don't think that we have an achievements API yet, right?

**Comment by haroldadmin** [comment]
I have now added tests as well, and squashed the two commits. Please review when you get the chance, @isabelcosta 😊

**Comment by haroldadmin** [comment]
@isabelcosta After our discussion I realized that we do have an achievements API. I'll add it and update the PR soon.
