### ISSUE TITLE
Simple webapp to generate .env file

### ISSUE THREAD

**Issue by daksha-aeer** [anitab-org/mentorship-backend#285]
**Is your feature request related to a problem? Please describe.**
I was working on the task to write a shell/bat script for setting up mentorship backend. While working on it I noticed several issues with this approach:
1. Separate scripts for windows and linux/Mac. This will be more difficult to maintain.
2. Cloning repository, accepting environment variables, installing pip dependencies, performing tests and running app were clubbed together. I feel they could be separated. For example, I don't see any logic in the script cloning the repo again. The script will itself come when the repo is cloned.
3. If any step fails or if any input is wrong the whole script must be run again.
4. No GUI!

**Describe the solution you'd like**
I propose a webapp to generate the .env file :)
![image](https://user-images.githubusercontent.com/50169911/70899292-5d04f300-201c-11ea-8570-e0e87017d7d0.png)

https://wireframepro.mockflow.com/view/M38561485d2d04548aeaffaf893cca52a1576485992547

#### Advantages
1. Graphical
2. Independent of operating system
3. Will eliminate typos. Eg. regular expression can be used for correct email.
4. Can be run locally or hosted online so users can directly generate file.

**Describe alternatives you've considered**
A python script instead of shell/bat script. This will be platform independent but not graphical.

**Additional context**
Ready to work on it :)

**Comment by isabelcosta** [comment]
@daksha-aeer thats an interesting idea! Thank you for creating this issue.
So how long, or how complex would this be? What would you use to do this simple app?
I'm thinking if this issue effort matches the potential gain that a contributor could have.

I did some research and I think flask will load the environment variables on the first run, from `.env` file (assuming you create it with this [environment variables](https://github.com/systers/mentorship-backend/wiki)). But I'm not sure it really works for any operating system 🤔

**Comment by daksha-aeer** [comment]
This is in relation to issue #223 . I can create a basic html + javascript + css page. It won't take much time. I think more features like systers logo, beautification could be added incrementally. Or should I do some research about frontend frameworks?

**Comment by Aaishpra** [comment]
@isabelcosta @daksha-aeer @vj-codes I loved this idea, and I too think it won't take much time to be executed and any simple web app (created using HTML, CSS, javascript) can be very beneficial for newcomers for setting up the application and will reduce the setup time and complexity for others too.

**Comment by isabelcosta** [comment]
@Aaishpra I think it could be more helpful to improve the README including these steps:

If we do something like this, then it would be useful not just for this project but for all of our project and should be done in a more generic way. In this way should be separate from this project.

I think this is a nice idea with good intentions, but I would prefer having more clear instructions on README, instead of creating a sub-app in this repository dedicated only to set env variables (additional code to maintain, that does not contribute directly to the roadmap of the project - yet to be clarified). Also because setting env variables is something you setup once, and then you don't need to change that often.

Create your `.env` file from our example file:
```
cp .env.example .env
```
Then edit the env variables following file X guide.

What do you think of better instructions in the README first as an "MVP" of this? Does it make sense?
I will close this for now, but feel free to create an issue to improve the README instructions about this.

cc @vj-codes

**Comment by Aaishpra** [comment]
Got it thanks for the explanation @isabelcosta  :hugs: , I too agree now that maintaining another application, which isn't adding anything else than setting up the .env variable for the project is not very beneficial and time-consuming for the project (considering we already have a lot of issues to manage here and another project means new issues and new bugs/feature), although I think the current readme instructions are quite clear for setting up the project and .env variable but I get what @isabelcosta is trying to say here as for the "better instructions in the README first as an MVP" for this feature.

@daksha-aeer if you get what @isabelcosta suggested above can you open the suggested issue and maybe work on it if you are interested as this issue already got closed.

**Comment by isabelcosta** [comment]
Cool @aadityamp01 ! I am happy you agree, but I want you to know that if you did not I would welcome your input 🤗
