### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#331]
**Is your feature request related to a problem? Please describe.**
Since Python 3.5 there's a very nice facilitation, so to say, that's really underused and underestimated in my opinion. This feature is called *type hints* and they are described in [PEP 484](https://www.python.org/dev/peps/pep-0484/).

### What are type hints?
Type hints are small thingies that are appended after declaring variable name and...they hint the type of the variable. Examples:
`age: int = 42`
`username: str = "iwonttellmyname"`
`relations: List[MentorshipRelationModel] = dao.list_relations()`

Their usage is totally optional, they don't have *any* impact on program flow during runtime. However, they're really helpful in the development phase. IDEs like PyCharm support type hints and notify developers when types don't match. It really improves the coding experience.

It's also noteworthy that type hints don't interfere with dynamic nature of Python. One can write
`age: int = "nope"` and the program will run the same as it would without the type hint.

**Describe the solution you'd like**
I'd like to add type hints wherever possible to our codebase. It will greatly improve quality of life

**Describe alternatives you've considered**
We can just continue to develop this project without type hints. Nothing really bad will happen.

**Comment by bartekpacia** [comment]
@isabelcosta What do you think about it? I'd like to work on it but need to make sure it's something we want :)

**Comment by isabelcosta** [comment]
@bartekpacia thank you for creating this issue which such great detail!

I think there were previous conversations about this, but I don't remember where and when this discussions occurred. I like this idea, because I like these things to be explicit, i think it makes debugging and understanding the code easier.

I think one of the concerns pointed out in the past, wast about having community standards, and we even has GSoC students think about this. By community standards I mean, doing python the same way in project X and project Y from Systers.

I will share on Slack, because this was talked before, but I approve this.

**Comment by bartekpacia** [comment]
Thanks for response @isabelcosta. I also like explicitness, (and python too - it's even stated in The Zen Of Python :)).
By approving I understand that I can submit a PR, right? They have no runtime effect, so there won't be any breaking changes.
