### ISSUE TITLE
Backend Service is not working

### ISSUE THREAD

**Issue by geekayush** [anitab-org/mentorship-backend#491]
**Describe the bug**
The backend service is not working.

**To Reproduce**
1. Download the apk
2. Try signing up or logging in
3. It says "Internal Server Error"

**Expected behavior**
I should have been on board

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 9

**Additional context**
I want to go through the Android Version of Mentorship System in order to prepare for Web Version of the same.

**Comment by isabelcosta** [comment]
This is a known issue @geekayush  :) Thank you for reporting this, in this way I can explain this on GitHub.

So there is an entire Zulip topic on this, among other messages.
- [Initial Zulip message about this (non-persistent-db topic)](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/non-persistent-db/near/188831229)
- [fixing-backend topic on Zulip](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/fixing-backend)

I can also update here, in short:
- The AWS deployment of the backend is currently unavailable and to be fixed. There are no current updates on this, as of now.
- So to mitigate this problem I deployed a temporary backend on Heroku. Also to allow contributors to still access the backend without having to set it up (either because you are a tester or an android developer that wants to just focus on android, etc..). Here it is: https://mentorship-backend-temp.herokuapp.com/ However, this is up until we fix the AWS deployment issue.
- I created an ongoing PR https://github.com/anitab-org/mentorship-android/pull/637 to change the backend URL on Android application, so contributors to android app don't have to worry about setting up the backend locally. Until this is merged if you want to test the apk, you may have to run the Android app on Android Studio and before that change the backend URL. I will let y'all know once the PR is merged.

Hope this clarifies any doubts you have :)

**Comment by geekayush** [comment]
Thanks, @isabelcosta. It sums up well. As I don't know much about Android I guess I would wait for the PR to get merged.

**Comment by isabelcosta** [comment]
@geekayush it will soon be merged :)

**Comment by isabelcosta** [comment]
@geekayush I think this issue is solved :D Can you please check it for yourself: https://github.com/systers/mentorship-android/raw/apk/app-debug.apk?

If you confirm this successfully, can you close this issue then?

**Comment by geekayush** [comment]
@isabelcosta Yes! It works totally fine now.
