### ISSUE TITLE
Fix description messages on Mentorship Relation

### ISSUE THREAD

**Issue by StergiosSozos** [anitab-org/mentorship-backend#554]
## Description
As a developer, i need to see the same way for displaying messages on the backend server. so that i can follow the same pattern on the messages im writing. Right now the messages are shown in 2 ways:
![image](https://user-images.githubusercontent.com/44146773/80616049-1c48cc00-8a49-11ea-9d46-33518902c3c5.png)
![image](https://user-images.githubusercontent.com/44146773/80616700-e35d2700-8a49-11ea-9611-9e3e2e082560.png)

### Update [Required]
Change the messages to either:
a){’message’: 'User is already an Admin.’}
or
b)User is already an Admin.
## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by StergiosSozos** [comment]
@isabelcosta can you suggest one of the 2 ways?
And can i be assgined to this issue?

**Comment by robotjellyzone** [comment]
Hi @StergiosSozos that's quite interesting issue and really a good catch you have done !! Actually, as far as i remember [as i have gone through the entire backend code earlier this week] this is due to the fact that somewhere  we were using fstring for responses and on other places we were just printing / returning the JSON responses but i think its good to use the fstring one as it follows the new coding  style ... But i am still not totally sure why this has been done in the code .. Only @isabelcosta can suggest !!

**Comment by StergiosSozos** [comment]
Thank you very much, @isabelcosta when you have time, please let me know which style to keep!

**Comment by isabelcosta** [comment]
@StergiosSozos this issue is valid, thank you for providing the screenshots, it was very helpful!
If the JSON response, is `{’message’: 'User is already an Admin.’}`, then that should appear there. I can assign this to you :)

**Comment by StergiosSozos** [comment]
Thank you for the immediate response. So we do need the {’message’: to appear. I'm fixing the changes on my previous PR and I will start this one next.
