### ISSUE TITLE
400 Responses does not list "Your email is invalid." message.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#562]
When we register a new user, if we entered  an invalid email address then we see the expected error message "Your email is invalid." but this message is not listed under 400 Responses.

1. Go to 'User-Register'
2. {
  "name": "testua",
  "username": "testua",
  "password": "testua123",
  "email": "voxij69223mailop7.com",
  "terms_and_conditions_checked": true,
  "need_mentoring": true,
  "available_to_mentor": true
}
3. Click on 'Execute'
4. Scroll down to 'Response'
![Screenshot (4)](https://user-images.githubusercontent.com/50888936/80869007-794bb880-8cbb-11ea-8d28-e44570ec3df7.png)

**Expected behavior**
All the error messages should be listed under the 400 error messages.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  Chrome

**Comment by Ritika5901234** [comment]
Hi @isabelcosta and @faznan3nazer - although I have been working on the similar issue #573 , can I get this issue assigned to me as well, if not its absolutely fine :-)

**Comment by evangelisilva** [comment]
@Ritika5901234 Go ahead!

**Comment by Ritika5901234** [comment]
@EvangeliSilva - thanks :-)

**Comment by isabelcosta** [comment]
@Ritika5901234 since you are already assigned to another first timer only issue, could you please leave this to another newcomer. You can help them solve the issue if needed and review the PR :) I can create other non newcomer issues so you can try those out.

@EvangeliSilva thank you for being so quick to help and respond, I'm just intervining here because this is a first timer only issue, having these as first timers only is what allows us to onboard new people into the codebase.

I will unassign this for now.

**Comment by Ritika5901234** [comment]
@isabelcosta - sure :-)

**Comment by aadityamp01** [comment]
Hello, @faznan3nazer and @isabelcosta  I am interested to work on this issue. If no one is working on it, will you please assign it to me?
Thanks.

**Comment by evangelisilva** [comment]
@aadityamp01 You are assigned 😊

**Comment by aadityamp01** [comment]
@EvangeliSilva Thanks.
