### ISSUE TITLE
Updating Readme.md 

### ISSUE THREAD

**Issue by sharur7** [anitab-org/mentorship-backend#856]
## Description
As a contributor,
I need no contradictions in the README file,
so that I won't be doubtful of the dependencies.
**Adding GitHub badge for forks and star.**
**Adding a license badge.**

## Mocks
mentorship-android already have these badges in README.md<br>
![Capture](https://user-images.githubusercontent.com/57194200/92597180-a68d2080-f2c4-11ea-9964-70f86fd7181e.PNG)

### Update [Required]
- [ ] GitHub Forks & Star badges
- [ ] License Badge

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

@vj-codes @PrashanthPuneriya I want to take up this issue as part of OSH. Please add the appropriate labels to it. I want to work on this issue. Thank You.

**Comment by vj-codes** [comment]
@Akanksha1212  You were there for yesterday's sync session right? the other badges that Isabel had mentioned are already present here . So should this be open or not?
cc: @Techno-Disaster

**Comment by guruc-134** [comment]
I'm new to opensource contribution and  would like to take up this issue and work on it.
Thank You

**Comment by isabelcosta** [comment]
@sharur7 thank you for proposing an improvement for this project 🤗 However, as @vj-codes said, in yesterday's meeting we agreed that these specific badges are not necessary. This is because you can see this in the GitHub interface when you visit the project's page.

bottom right, you see the license and top right you see the stars and forks. So I will close this issue for now :)

![image](https://user-images.githubusercontent.com/11148726/92662622-23d18900-f2f7-11ea-8803-da14ac16ca68.png)

Thank you again @sharur7 
cc @guruc-134
